export const API_ENDPOINTS = {
  AUTH: {
    NONCE: '',
    VERIFY_SIGNATURE: '',
  },
  PRIVATE: {
    POST_SUBSCRIBE_PLAN: '',
    GET_NONCE: 'api/v1/user/get-address-nonce/',
    GET_SIGNATURE: 'api/v1/user/verify-signature',
    GET_PROFILE_NFT: '',
    GET_GENERATE_NFT: 'api/v1/ai-image/get-image?',
    GET_USER_DATA: 'api/v1/user/profile?',
    CREATE_NFT: 'api/v1/collectible',
    GET_GENERATE_TAB_DATA: 'api/v1/ai-image/get-generated-image?',
    GET_MINTED_TAB_DATA: 'api/v1/collectible/created?',
    GET_FAVORITE_TAB_DATA: 'api/v1/collectible/favourite?',
    IMAGE_UPLOAD: 'api/v1/helper/upload-image?',
    UPDATE_USER_DATA: 'api/v1/user/update',
    DO_LIKE: 'api/v1/like',
    GET_LISTING_LIST: 'api/v1/collectible/on/sale?',
    PUT_ON_SALE: 'api/v1/collectible/put-on-sale-item',
    VIEW_COUNT: 'api/v1/collectible/view',
    GET_USER_PLAN_HISTORY: 'api/v1/user/get-plan-history?',
    SAVE_EVENT_NFT: 'api/v1/collectible/save-collectible-event',
    SAVE_SOLAV_TRANSFER: 'api/v1/payment/save-solav-transfer',
    CREATE_COLLECTION: 'api/v1/collection',
    UPDATE_COLLECTION_ADDRESS: 'api/v1/collection/update-address',
  },
  PUBLIC: {
    GET_EXAMPLE_NFT: 'api/v1/ai-image/historic-images?',
    GET_SUBSCRIPTION_LIST: 'api/v1/plans/get-plans',
    SUBSCRIBE_PLAN: 'api/v1/payment/checkout',
    GET_GENERATE_NFT: '',
    POST_EMAIL_SUBSCRIBE: 'api/v1/helper/email-subscribe',
    GET_SEARCH: 'api/v1/collectible/explore',
    GET_ITEM_DETAILS: 'api/v1/collectible/detail?',
    GET_ITEM_ACTIVITY: 'api/v1/collectible/history?',
    GET_PLATFORM_FEE: 'api/v1/plans/platform-fee?',
    GET_SOLAV_RATE_CONVERSION: 'api/v1/rate-conversion',
    GET_CUSTOM_COLLECTION_LIST: 'api/v1/collection/list?',
    GET_COLLECTION_DETAILS: 'api/v1/collection/details?',
    GET_COLLECTION_ITEM_AND_ACTIVITY: 'api/v1/collection/collection-activity?',
  },
} as const

export const QUERIES_KEY = {
  AUTH: {
    NONCE: 'get-user-nonce',
    VERIFY_SIGNATURE: 'verify-signature',
  },
  PRIVATE: {
    POST_SUBSCRIBE_PLAN: '',
    GET_PROFILE_NFT: 'profile-nft',
    GET_USER_DATA: 'profile-nft',
    CREATE_NFT: 'collectible',
  },
  PUBLIC: {
    GET_EXAMPLE_NFT: 'example-nft',
    GET_GENERATE_NFT: 'generate-nft',
    GET_SUBSCRIPTION_LIST: 'subscription-list',
    SUBSCRIBE_PLAN: 'add-plan',
    POST_EMAIL_SUBSCRIBE: 'email-subscribe',
    GET_SEARCH: 'collectible-explore',
    GET_PLATFORM_FEE: 'network_id',
  },
} as const
